version: "3"
services:
  database:
    image: mysql:5.7
    platform: linux/amd64 # arm64 환경을 위한 platform 명시
    environment:
      MYSQL_ROOT_PASSWORD: store_mgmt_root_pass
      MYSQL_DATABASE: store_mgmt
      MYSQL_USER: store_mgmt_admin
      MYSQL_PASSWORD: store_mgmt_admin_pass
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD" ]
      interval: 2s
      timeout: 20s
      retries: 10
  app:
    build:
      dockerfile: Dockerfile.local
      context: ./
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
